#
# Copyright 2012-2013 Ettus Research LLC
#

##################################################
# my blocks library
##################################################
MY_BLOCKS_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/my_blocks/, \
my_complex_to_magsq.v \
my_correlator.v \
my_delay_power_block.v \
my_delay_sample_in.v \
my_moving_sum.v \
my_peak_detector.v \
my_window.v \
))
